In [1]:
import numpy as np

In [2]:
ex1 = np.array([[2,3,5,7],[1,9,24,15],[5,12,19,21]])
print(ex1)

[[ 2  3  5  7]
 [ 1  9 24 15]
 [ 5 12 19 21]]


In [3]:
print(np.size(ex1))

12


In [4]:
ex2 = np.zeros([3,4])
print(ex2)
print("add 5 : ",ex2+5)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
add 5 :  [[5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]]


In [5]:
print(ex1.reshape([4,3]))

[[ 2  3  5]
 [ 7  1  9]
 [24 15  5]
 [12 19 21]]


In [6]:
print(ex1[1,2])
print(ex1[2,0])
print(ex1[0,3])

24
5
7


In [7]:
print("row sum : ",np.sum(ex1,axis =1))
print("col sum : ",np.sum(ex1,axis =0))

row sum :  [17 49 57]
col sum :  [ 8 24 48 43]


In [8]:
ex3 = ex1.ravel()
print(ex3)

[ 2  3  5  7  1  9 24 15  5 12 19 21]


In [9]:
print("min : ",np.min(ex3))
print("max : ",np.max(ex3))
print("sum : ",np.sum(ex3))

min :  1
max :  24
sum :  123


In [10]:
ex4 = np.arange(2,25,2)
print(ex4)

[ 2  4  6  8 10 12 14 16 18 20 22 24]


In [11]:
ar1 = np.array([[1,2,3,5],[19,24,15,10],[15,22,9,21]])
print("hstack : ",np.hstack((ex1,ar1)))
print("vstack : ",np.vstack((ex1,ar1)))

hstack :  [[ 2  3  5  7  1  2  3  5]
 [ 1  9 24 15 19 24 15 10]
 [ 5 12 19 21 15 22  9 21]]
vstack :  [[ 2  3  5  7]
 [ 1  9 24 15]
 [ 5 12 19 21]
 [ 1  2  3  5]
 [19 24 15 10]
 [15 22  9 21]]
