In [20]:
import numpy as np

In [21]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [22]:
print(a[1])

2


In [24]:
#slice
print(a[0:2])

[1 2]


In [17]:
# 2d
a = np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [18]:
print(a[1,1])

5


In [5]:
b = np.zeros(4)
print(b)

[0. 0. 0. 0.]


In [6]:
# 2d
b = np.zeros((4,5))
print(b)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [7]:
# to get n-dimension
print(b.ndim)

2


In [8]:
c = np.ones(5)
print(c)

[1. 1. 1. 1. 1.]


In [26]:
a1 = np.arange(0,20,2)
print(a1)

[ 0  2  4  6  8 10 12 14 16 18]


In [27]:
l1 = np.linspace(0,10,20)
print(l1)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


In [28]:
r1 = np.random.rand(5,5)
print(r1)

[[0.39449332 0.11221317 0.45870911 0.31440519 0.81308007]
 [0.66132834 0.64378812 0.25305305 0.69288017 0.0230611 ]
 [0.95632638 0.70221361 0.98486257 0.11576415 0.64483242]
 [0.44007684 0.90397181 0.93831861 0.46070759 0.14913333]
 [0.51360247 0.05938222 0.50890032 0.24747972 0.50835291]]


In [31]:
print(a1.reshape(5,2))
print(a1)

[[ 0  2]
 [ 4  6]
 [ 8 10]
 [12 14]
 [16 18]]
[ 0  2  4  6  8 10 12 14 16 18]


In [30]:
a2 = np.arange(0,10,1)
print(a2)
a2.resize(5,2)
print(a2)

[0 1 2 3 4 5 6 7 8 9]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [33]:
a1 = np.arange(1,11)
a2 = np.arange(11,21)
print(a1)
print(a2)
print("add : ",(a1+a2))
print("sub : ",(a2-3))

[ 1  2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19 20]
add :  [12 14 16 18 20 22 24 26 28 30]
sub :  [ 8  9 10 11 12 13 14 15 16 17]


In [36]:
ax1 = np.array([[2,4,6,8],[3,1,6,2],[4,7,2,6]])
print(ax1)
print("sum : ",np.sum(ax1))
print("col sum : ",np.sum(ax1,axis =0))
print("row sum : ",np.sum(ax1,axis =1))

[[2 4 6 8]
 [3 1 6 2]
 [4 7 2 6]]
sum :  51
col sum :  [ 9 12 14 16]
row sum :  [20 12 19]


In [ ]:
print(ax1.ravel())

In [39]:
ax2 = np.array([[1,5,6,7],[6,9,0,3],[4,3,6,8]])
print("horizontal concat : ",np.hstack((ax1,ax2)))
print("vertical concat : ",np.vstack((ax1,ax2)))

horizontal concat :  [[2 4 6 8 1 5 6 7]
 [3 1 6 2 6 9 0 3]
 [4 7 2 6 4 3 6 8]]
vertical concat :  [[2 4 6 8]
 [3 1 6 2]
 [4 7 2 6]
 [1 5 6 7]
 [6 9 0 3]
 [4 3 6 8]]
